server:
  port: 8761

eureka:
  instance:
    hostname: 192.168.18.7
    ip-address: 192.168.18.7
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #ip:port

  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/